spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbplanner
    username: userpg
    password: ut3nt3#
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    enabled: true
    path: /rest-api-docs
  swagger-ui:
    path: /swagger-ui

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 600000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
cors:
  origins: 'http://localhost:4200'
